name: Publish Build

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - { name: 'Set up JDK 17', uses: actions/setup-java@v2, with: { distribution: 'adopt', java-version: '17' } }
      - name: Upload to Maven
        run: ./gradlew clean publish
        env:
          {
            MAVEN_PASSWORD: "${{secrets.MAVEN_PASSWORD}}",
            MAVEN_URL: "${{secrets.MAVEN_URL}}",
            MAVEN_USER: "${{secrets.MAVEN_USER}}"
          },